name: Random Stuff
favicon: null
layout_spectrum: 0.34247
typography_spectrum: 0.19764
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#821937'
    - '#ffffd9'
    - '#aaaaaa'
    - '#a35068'
    - '#ff8080'
  brandStrength: 0.6030884094070643
  lightness: 0.442372583784163
  saturation: 0.5504740062169731
  rhythmicContrast: 0.6938298102468252
purpose: []
