name: Random Stuff
favicon: null
layout_spectrum: 0.08092696079984307
typography_spectrum: 0.7475397686939687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6030884094070643
  lightness: 0.442372583784163
  saturation: 0.5504740062169731
  rhythmicContrast: 0.6938298102468252
purpose: []
